CREATE TABLE WEBSOCKET_SEAT(
		WEB_SEAT_NO IDENTITY,
		WEB_SEAT_ROW VARCHAR(255),
		WEB_SEAT_COL VARCHAR(255)
);

CREATE TABLE WEBSOCKET_TICKET(
		WEB_TICKET_NO IDENTITY,
		WEB_SCREENING_NO INT,
		WEB_SEAT_NO INT
);

CREATE TABLE WEBSOCKET_SCREENING(
		WEB_SCREENING_NO IDENTITY,
		WEB_SCREENING_DATE DATE,
		WEB_SCREENING_TIME VARCHAR(255),
		WEB_MOVIE_NO INT,
		WEB_HALL_NO INT,
		WEB_THEATER_NO INT
);

--ALTER TABLE WEBSOCKET_TICKET ADD CONSTRAINT IDX_WEBSOCKET_TICKET_FK0 FOREIGN KEY (WEB_SEAT_NO) REFERENCES WEBSOCKET_SEAT (WEB_SEAT_NO);
--ALTER TABLE WEBSOCKET_TICKET ADD CONSTRAINT IDX_WEBSOCKET_TICKET_FK1 FOREIGN KEY (SCREENING_NO) REFERENCES WEBSOCKET_SCREENING (SCREENING_NO);
